#ifndef __simple_dor_h__
#define __simple_dor_h__


//  code generated by fsm_gen
// generated automatically
// coded last modification:        $CODED_LAST_MODIF  desactivated, lots of false notifications
// pythonscript last modification: $SCRIPT_LAST_MODIF


#include "support/alarm.h"
#include "support/signalslot.hpp"



namespace fsmgen_simple_dor {
    class abstract_status;
};





namespace testing{


class simple_dor   : public mtk::SignalReceptor
{
    mtk::non_copyable nc;
    typedef  simple_dor  CLASS_NAME;


public:
    simple_dor ();
    virtual ~simple_dor ();

    //  INPUT
    void open           ( const int&          key          );
    void close          ( const int&          key          );


    //  OUTPUT
    mtk::Signal<  > sig_opened;
    mtk::Signal<  > sig_closed;


    //  ACCESS



private:
    //  current_status
    mtk::CountPtr<fsmgen_simple_dor::abstract_status>      current_status;
    void on_new_status (mtk::CountPtr<fsmgen_simple_dor::abstract_status>  new_status);

    //  keep temp status
    mtk::list<mtk::CountPtr<fsmgen_simple_dor::abstract_status> >     queue_temp_status;
    void on_keep_temp_status (void);
    void on_remove_temp_status (void);
};





};   //  namespace testing


#endif // __simple_dor_h__


