:cpp: {basebackend@docbook:c++:cpp}
== projects_examples

On +examples/pr_make+ dir we have some full projects examples

On each example there are detailed documentation


[NOTE]
To avoid loops on directory tree, instead of linking mtk, it's linked folders and files inside mtk

[jle_temp_and_run]
+++++++++++++++++
run=[ ("echo '--------'",'ls.txt', 'wt'), 
      ("ls {docdir}/../../examples/prj_make | grep -v makefile", 'ls.txt', 'at'),
      ("echo '--------'",'ls.txt', 'at')]
print ''
+++++++++++++++++

.examples/prj_make
include::/tmp/adoc/ls.txt[]



=== emarket

* This is a non trivial example
* It's a basic electronic market to test the system with trading and prices
* There is an especific document on +emarket/doc+ folder and compiled on +mtk/doc+



=== HouseLight

* This is a simple and small example
* There are a small document (also as example) +
  It could serve as document example
* This program will send the central keep alive to servers and clients
* See the document in doc and source of document on src
+
.examples/prj_make/houselight/src/main.cpp
[source,{cpp}]
----
include::../../examples/prj_make/houselight/src/main.cpp[]
----


=== ACS

Access Control System

* It controls login
* Users and passwords maintenance
* Generate sessions id
* Coordination of sessions list with others servers
* Code on... examples/prj_make/acs/src/
* Doc on... examples/prj_make/acs/doc/

=== Product loader


* It will listen information from products (as prices i.e.) and will keep in memory this information
* Clients and other servers, can request for product status



=== Account manager server

* This process can work on two diferent configurations
.. Receiving the account grants and sending the confirmations (a request can be responsed by several +account managers+, so it's not possible to work with request response pattern)
.. Receiving order request and adding the +reject description+ field on +oms_+ messages
* The file with accounts and grants, is a +YAML+ file
* On grants, +account_name+ and +client_code+ from +account_info+ is a regular expresion pattern
** +^+  and +$+ indicating begining and end of string, will be added by program. Do not add them yourselft
