 
.PHONY : all
all:
	make -C ex1 build_msg
	make -C ex1 this
	@echo .
	@echo .
	@echo '-----------------------------------------------------'
	@echo .
	ex1/bin/testing
	@echo .
	@echo '-----------------------------------------------------'
	@echo .
