version: 1
amqp_url: amqp:tcp:192.168.7.21:6684
rules__error2warning:
  - re_rule: received update with no changes  { market:M3  product
    frequency: "2h "
    n_received: 43
    description: description
    start_time: 0s
    end_time: "1d "
    last_notified: 2011-12-15 10:14:44.105
  - re_rule: received keep alive with invalid session id
    frequency: "2h "
    n_received: 27
    description: description
    start_time: 0s
    end_time: "1d "
    last_notified: 2011-12-15 10:51:13.559