:cpp: {basebackend@docbook:c++:cpp}
=== Admin

* This component will work with client and servers
* It has an internal singleton on implementation (.cpp) but the interface has no objetcs, only "functions" call, grouped by namespaces.
* It will...
** Send the keep alive
** Send the enter and exit messages
** Check the received keep alive
** Check local fluctuations
** Get the +AlarmMsg+ to write in log and send by network
** Manage the configuration file
*** The process will access to the configuration file using this component
** Manage commands and responses
** etc...
* That's the interface
+
.components/admin/admin.h
[source,{cpp}]
----
include::../../components/admin/admin.h[]
----



==== Examples

* Source code
+
.examples/onefile/components/admin/ex_admin.cpp
[source,{cpp}]
----
include::../../../examples/onefile/components/admin/ex_admin.cpp[]
----
+
* Configuration file for client
+
.examples/onefile/components/admin/config.cfg
----
include::../../../examples/onefile/components/admin/config.cfg[]
----
* Configuration file for server
+
.examples/prj_make/houselight/etc/config.cfg
----
include::../../../examples/prj_make/houselight/etc/config.cfg[]
----



==== HouseLigh

* As this program is very small, it serves as an admin example working on client side
+
.examples/prj_make/houselight/src/main.cpp
[source,{cpp}]
----
include::../../../examples/prj_make/houselight/src/main.cpp[]
----

[NOTE]
On servers, the +app_name+ will be readed from config file. +
This will let run one process several times (with different name)


