= Messages

Here we have the messages definitions (and in some cases the state diagrams) from component messages.



[width="75%", cols="1, 2" , options=""]
|==========================================================
| lib version |  **
include::../../../VERSION[]
**

| Writter   |   José Luis Esteban

| Creation date |   2011-05-16

| Generated |   {docdate} {doctime}

| Doc name | {docname}

| Doc dir | {docdir}

| Doc file | {docfile}


|========================================================

<<<





//////////////
[jle_temp_and_run]
++++++++++++++++++++++++
run=[('python generate_messages_doc.py', 'generate_messages_doc.txt', 'wt')]

print ''

file_name='generate_messages_doc.py'


# this is our testing script
import os
import re



def process_path(path) :
    dirList=os.listdir(path)
    for fname in dirList:
        full_name = os.path.join(path, fname)
        if os.path.isdir(full_name)  and  fname != 'tools':
            process_path (full_name)
        else :
            if os.path.splitext(fname)[1] == '.msg' :
                file_msg = re.match('.*/components/(.*)', full_name)
                print '== ' + file_msg.group(1) + '\n'
                ##print full_name +'\n'
                print '---------'
                print 'include::' + full_name + '[]'
                print '---------\n\n'
    
    
    
   
process_path('{docdir}/../../../src/components')


+++++++++++++++++++++++++

include::/tmp/adoc/generate_messages_doc.txt[]

//////////////



== General INFO

=== ADDRESSES

* CLIPROD
* SRVPROD

* CLITESTING
* SRVTESTING

=== Routing keys
* We will try to keep the +client+ on second field and +market+ on third field (specially on output messages) +
  Ex:  PUB.PRC.<mtk>.PROD,   PUB.ADM.GEN...

CLI ->  SYS::
+
|=====================
| RQ.<from_client>.#
|=====================

CLI <-  SYS::
+
|=====================
| RS.<client>.<machine>.<process_uuid>.<request_code>#   |    Request responses
| CONF.<client>.#   |    Permanent topics responses (as order confirmations)
| PUB.#   |    One direcction publications
|=====================

CLI <-->  SYS::
+
|=====================
| ADM.#   |    keep alives, request commands, response commands
|=====================

* +PUB+ will be used on messages sent to many. Broadcast with no response and therefore no end response
* +CONF+ to send messages to many but they depend from any request or previus suscription information and the suscription is _permanent_. +
  Orders confirmation for example
* +REQ+ is for request responses and request confirmation patterns
* +REP+ responses of request response pattern. _Non permanent_ suscriptions

[NOTE]
The subject identify a message that can be sent or received directly

=== Message name convention
|=====================
| req_...   |    request (not necessarily request response, could be a request confirmation)
| res_...   |    responses (from request responses)
| conf_...  |    confirmations (as order confirmations)
| pub_...   |    publications (as prices, keepalives, etc...)
|=====================


=== YAML support
* All generated messages and submessages overload operators +>>+ and +<<+ with +YAML+ classes





include::request_response_pattern.adoc[]


== Common

.Common submessages for several kind of components
-----
include::../../../src/components/msg_common.msg[]
-----

.Support code for common messages
-----
include::../../../src/components/msg_common_support.h[]
-----


== Admin

.components/admin/msg_admin.msg
-----
include::../../../src/components/admin/msg_admin.msg[]
-----



== ACS

* Access Control System


=== Client side

.Orders LS status diagram
["graphviz", "fsm_cli_acs.png"]
-----------
include::../../../src/components/acs/cli/fsm_cli_acs.dot[]
------------

.components/acs/msg_acs.msg
-----
include::../../../src/components/acs/msg_acs.msg[]
-----





== Trading

=== Common

* Inheritance diagram with some messages

["graphviz", "trading_inheritance_diagram0.png"]
-----------
digraph trading_inheritance  {
    rankdir=LR;
    node [shape = circle, fontsize=10, fixedsize=true width=0.8];

    RQ_XX
    CF_XX  ->  RJ_XX
}
-----------

["graphviz", "trading_inheritance_diagram1.png"]
-----------
digraph trading_inheritance {
    rankdir=LR;

    node [shape = circle, fontsize=10, fixedsize=true width=0.8];

    RQ_XX  ->  RQ_XX_LS
    RQ_XX_LS  ->  RQ_NW_LS  
    RQ_XX_LS  ->  RQ_MD_LS
    RQ_XX_LS  ->  RQ_EX_LS

    RQ_XX  ->  RQ_XX_MK
    RQ_XX_MK  ->  RQ_NW_MK
    RQ_XX_MK  ->  RQ_MD_MK
    RQ_XX_MK  ->  RQ_EX_MK

    RQ_XX  ->  RQ_XX_SL
    RQ_XX  ->  RQ_XX_SM

}
-----------

["graphviz", "trading_inheritance_diagram2.png"]
-----------
digraph trading_inheritance {
    rankdir=LR;

    node [shape = circle, fontsize=10, fixedsize=true width=0.8];

    CF_XX  ->  CF_XX_LS
    CF_XX_LS  ->  CF_NW_LS  
    CF_XX_LS  ->  CF_MD_LS
    CF_XX_LS  ->  CF_EX_LS

    CF_XX  ->  CF_XX_MK
    CF_XX_MK  ->  CF_NW_MK
    CF_XX_MK  ->  CF_MD_MK
    CF_XX_MK  ->  CF_EX_MK

    CF_XX  ->  CF_XX_SL
    CF_XX  ->  CF_XX_SM

    CF_XX_LS  ->  RJ_NW_LS  
    CF_XX_LS  ->  RJ_MD_LS
}
-----------



* Common submessages for trading
+
.src/components/trading/msg_trd_common.msg
-----
include::../../../src/components/trading/msg_trd_common.msg[]
-----

/*
* Support code for trading client messages
+
.src/components/trading/msg_trd_common_support.h
-----
include::../../../src/components/trading/msg_trd_common_support.h[]
-----
*/


=== Limit orders

* Online trading Limit Orders client messages
+
.msg_trd_cli_ls.msg
-----
include::../../../src/components/trading/msg_trd_cli_ls.msg[]
-----


* Orders LS status diagram
+
["graphviz", "components_trading_o_ls.png"]
-----------
include::../../../src/components/trading/trd_cli_ls.dot[]
------------


=== Market orders

* Online trading +market+ Orders client messages
+
.msg_trd_cli_mk.msg
-----
include::../../../src/components/trading/msg_trd_cli_mk.msg[]
-----


* Orders MK status diagram
+
["graphviz", "components_trading_o_mk.png"]
-----------
include::../../../src/components/trading/trd_cli_mk.dot[]
------------




=== OMS

* Trading Limit Orders OMS messages (added permision filter fields)
. msg_trd_oms_rq.msg
+
-----
include::../../../src/components/trading/msg_trd_oms_rq.msg[]
-----


== Prices

.Online prices messages
-----
include::../../../src/components/prices/msg_prices.msg[]
-----
