= Messages


Here we have the messages definitions (and in some cases the state diagrams) from component messages.



//////////////
[jle_temp_and_run]
++++++++++++++++++++++++
run=[('python generate_messages_doc.py', 'generate_messages_doc.txt', 'wt')]

print ''

file_name='generate_messages_doc.py'


# this is our testing script
import os
import re



def process_path(path) :
    dirList=os.listdir(path)
    for fname in dirList:
        full_name = os.path.join(path, fname)
        if os.path.isdir(full_name)  and  fname != 'tools':
            process_path (full_name)
        else :
            if os.path.splitext(fname)[1] == '.msg' :
                file_msg = re.match('.*/components/(.*)', full_name)
                print '== ' + file_msg.group(1) + '\n'
                ##print full_name +'\n'
                print '---------'
                print 'include::' + full_name + '[]'
                print '---------\n\n'
    
    
    
   
process_path('{docdir}/../../../src/components')


+++++++++++++++++++++++++

include::/tmp/adoc/generate_messages_doc.txt[]

//////////////



== General INFO

=== ADDRESSES

* CLIPROD
* SRVPROD

* CLITESTING
* SRVTESTING

=== Routing keys
* We will try to keep the +client+ on second field and +market+ on third field (specially on output messages) +
  Ex:  PUB.PRC.<mtk>.PROD,   PUB.ADM.GEN...

CLI ->  SYS::
+
|=====================
| RQ.<from_client>.#
|=====================

CLI <-  SYS::
+
|=====================
| RS.<client>.<machine>.<process_uuid>.<request_code>#   |    Request responses
| CONF.<client>.#   |    Permanent topics responses (as order confirmations)
| PUB.#   |    One direcction publications
|=====================

CLI <-->  SYS::
+
|=====================
| ADM.#   |    keep alives, request commands, response commands
|=====================

* +PUB+ will be used on messages sent to many. Broadcast with no response and therefore no end response
* +CONF+ to send messages to many but they depend from any request or previus suscription information and the suscription is _permanent_. +
  Orders confirmation for example
* +REQ+ is for request responses
* +REP+ responses of request response pattern. _Non permanent_ suscriptions


include::request_response_pattern.adoc[]


== Common

.Common submessages for several kind of components
-----
include::../../../src/components/msg_common.msg[]
-----

.Support code for common messages
-----
include::../../../src/components/msg_common_support.h[]
-----


== Admin

.components/admin/msg_admin.msg
-----
include::../../../src/components/admin/msg_admin.msg[]
-----





== Trading

.Common submessages for trading
-----
include::../../../src/components/trading/msg_trd_common.msg[]
-----


.Support code for trading client messages
-----
include::../../../src/components/trading/msg_trd_common_support.h[]
-----



.Online trading Limit Orders client messages
-----
include::../../../src/components/trading/msg_trd_cli_ls.msg[]
-----


.Orders LS status diagram
["graphviz", "components_trading_o_ls.png"]
-----------
include::../../../src/components/trading/trd_cli_ls.dot[]
------------



.Trading Limit Orders OMS messages (added permision filter fields)
-----
include::../../../src/components/trading/msg_trd_oms_rq.msg[]
-----


== Prices

.Online prices messages
-----
include::../../../src/components/prices/msg_prices.msg[]
-----
