.PHONY : default
default:
	@echo  choose a target   test, 






.PHONY : test
test:
	rm -rf temp; mkdir -p temp; cd temp; mkdir -p bin; cd bin; qmake ../../ex_min_qt/src/ex_min_qt.pro; make; ./ex_min_qt
	rm -rf temp; mkdir -p temp; cd temp; mkdir -p bin; cd bin; qmake ../../ex_send_order/src/ex_send_order.pro; make; ./ex_send_order
