
.PHONY : all
all:
	make -C simple_dor fsm
	make -C simple_dor release
	@echo .
	@echo .
	@echo '-----------------------------------------------------'
	@echo .
	simple_dor/bin/testing
	@echo .
	@echo '-----------------------------------------------------'
	@echo .

	make -C simple_dor2 fsm
	make -C simple_dor2 release
	@echo .
	@echo '-----------------------------------------------------'
	@echo .
	simple_dor2/bin/testing
	@echo .
	@echo '-----------------------------------------------------'
	@echo .

	make -C simple_dor3 fsm
	make -C simple_dor3 release
	@echo .
	@echo '-----------------------------------------------------'
	@echo .
	simple_dor3/bin/testing
	@echo .
	@echo '-----------------------------------------------------'
	@echo .

	make -C simple_dor4 fsm
	make -C simple_dor4 release
	@echo .
	@echo '-----------------------------------------------------'
	@echo .
	simple_dor4/bin/testing
	@echo .
	@echo '-----------------------------------------------------'
	@echo .


	make -C simple_dor5 fsm
	make -C simple_dor5 release
	@echo .
	@echo '-----------------------------------------------------'
	@echo .
	simple_dor5/bin/testing
	@echo .
	@echo '-----------------------------------------------------'
	@echo .


	make -C simple_dor6 fsm
	make -C simple_dor6 release
	@echo .
	@echo '-----------------------------------------------------'
	@echo .
	simple_dor6/bin/testing
	@echo .
	@echo '-----------------------------------------------------'
	@echo .


	make -C simple_dor7 fsm
	make -C simple_dor7 release
	@echo .
	@echo '-----------------------------------------------------'
	@echo .
	simple_dor7/bin/testing
	@echo .
	@echo '-----------------------------------------------------'
	@echo .
