 
.PHONY : all
all:
	make -C simple_dor fsm
	make -C simple_dor this
	@echo .
	@echo .
	@echo '-----------------------------------------------------'
	@echo .
	simple_dor/bin/testing
	@echo .
	@echo '-----------------------------------------------------'
	@echo .

	make -C simple_dor2 fsm
	make -C simple_dor2 this
	@echo .
	@echo '-----------------------------------------------------'
	@echo .
	simple_dor2/bin/testing
	@echo .
	@echo '-----------------------------------------------------'
	@echo .

	make -C simple_dor3 fsm
	make -C simple_dor3 this
	@echo .
	@echo '-----------------------------------------------------'
	@echo .
	simple_dor3/bin/testing
	@echo .
	@echo '-----------------------------------------------------'
	@echo .

	make -C simple_dor4 fsm
	make -C simple_dor4 this
	@echo .
	@echo '-----------------------------------------------------'
	@echo .
	simple_dor4/bin/testing
	@echo .
	@echo '-----------------------------------------------------'
	@echo .


	make -C simple_dor5 fsm
	make -C simple_dor5 this
	@echo .
	@echo '-----------------------------------------------------'
	@echo .
	simple_dor5/bin/testing
	@echo .
	@echo '-----------------------------------------------------'
	@echo .


	make -C simple_dor6 fsm
	make -C simple_dor6 this
	@echo .
	@echo '-----------------------------------------------------'
	@echo .
	simple_dor6/bin/testing
	@echo .
	@echo '-----------------------------------------------------'
	@echo .


	make -C simple_dor7 fsm
	make -C simple_dor7 this
	@echo .
	@echo '-----------------------------------------------------'
	@echo .
	simple_dor7/bin/testing
	@echo .
	@echo '-----------------------------------------------------'
	@echo .
