.PHONY : default
default:
	@echo  choose a target   test,






.PHONY : test
test:
	make -C support/ test
	make -C sockets/ test
	make -C yaml/ test
	make -C fb/  test
	make -C qpid/  test
	make -C components/  test

