:cpp: {basebackend@docbook:c++:cpp}

=== Components -> Trading



==== Cli Orders  LS

  components/trading/trd_cli_ls.h
  components/trading/trd_cli_ls.cpp


* This component has been generated with +fsm_gen+ from +trd_cli_ls.fsm+
* It will control the flow and keep historic per limit simple order
* It's allowed to request consecutive modifications and consecutive cancelations
+
.Orders LS status diagram
["graphviz", "components_trading_o_ls.png"]
-----------
include::../../../components/trading/trd_cli_ls.dot[]
------------
+
* The interfaz is...
+
[source,{cpp}]
----
include::../../../components/trading/trd_cli_ls.h[]
----
+
* The code (dsl fsm_gen) is...
+
.trd_cli_ls.fsm
[source,{cpp}]
----
include::../../../components/trading/trd_cli_ls.fsm[]
----

==== Cli orders LS example
.examples/onefile/components/trading/test_trd_cli_ls.cpp
[source,{cpp}]
----
include::../../../../examples/onefile/components/trading/test_trd_cli_ls.cpp[]
----

==== Cli Order book

* It will keep the orders
* New orders have to be created using it
* Orders manipulation can be managed easily with this component
* It's not a class, it's not a singleton, just a module
* The interfaz is...
+
.trd_cli_ord_book.h
[source,{cpp}]
----
include::../../../components/trading/trd_cli_ord_book.h[]
----
+
* Look the return reference on +get_sig_new_order_ls_created(void)+. It means, you have to use it inmediatly, never save the reference for a future use in a diferent part of program
