ADMIN:
  IdReloj: 4443
  ProcessName: HOLA_PRUEBA
  Production: false  # A partir de aquí, pueden leerse de global (comunes) o quizá deben
  Market: ~
  TibcoDaemon: 128.2.254.100:7500
  TibcoNetwork: ~
  TibcoServices:
    Client: 03
    Server: 02
    Service: 01
    Other: 07
    Pepe: 09